import { sanitizeEmailHtml } from "@/lib/emailing-html";
import type { CrmReleaseRow, Json } from "@/lib/supabase/types";

function escapeHtml(value: string) {
  return value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character] ?? character);
}

export function releaseList(value: Json): string[] {
  return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string" && Boolean(item.trim())).map((item) => item.trim()) : [];
}

export function renderAtriumOneReleaseEmail({ release, origin, introOverride }: { release: CrmReleaseRow; origin: string; introOverride?: string | null }) {
  const section = (title: string, items: string[], color: string) => items.length ? `<tr><td style="padding:0 38px 26px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #ebe5f3;border-radius:18px;background:#ffffff"><tr><td style="padding:24px 24px 10px"><div style="font-size:12px;line-height:1.2;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:${color}">${escapeHtml(title)}</div></td></tr>${items.map((item) => `<tr><td style="padding:8px 24px 14px"><table role="presentation" cellpadding="0" cellspacing="0"><tr><td valign="top" style="padding-top:6px"><span style="display:block;width:8px;height:8px;border-radius:8px;background:${color}"></span></td><td style="padding-left:13px;font-size:15px;line-height:1.65;color:#3f3948">${escapeHtml(item)}</td></tr></table></td></tr>`).join("")}</table></td></tr>` : "";
  const intro = introOverride?.trim() || release.email_intro?.trim() || release.summary;
  const base = origin.replace(/\/$/, "");
  const version = release.version || new Date(`${release.release_date}T12:00:00`).toLocaleDateString("fr-FR");
  const html = `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escapeHtml(release.email_subject || release.title)}</title><style>@media(max-width:640px){.email-shell{width:100%!important}.pad{padding-left:22px!important;padding-right:22px!important}.title{font-size:30px!important}}</style></head><body style="margin:0;padding:0;background:#f5f2f8;font-family:Arial,Helvetica,sans-serif;color:#211432"><div style="display:none;max-height:0;overflow:hidden">${escapeHtml(release.summary)}</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f5f2f8"><tr><td align="center" style="padding:28px 12px"><table class="email-shell" role="presentation" width="640" cellpadding="0" cellspacing="0" style="width:640px;max-width:640px;border-radius:28px;overflow:hidden;background:#ffffff;box-shadow:0 16px 48px rgba(38,20,58,.1)"><tr><td class="pad" style="padding:30px 38px;background:#211432"><table role="presentation" width="100%"><tr><td><img src="${escapeHtml(`${base}/atriumone-logo.webp`)}" width="46" height="46" alt="AtriumOne" style="display:block;width:46px;height:46px;object-fit:contain"></td><td align="right" style="font-size:12px;font-weight:800;letter-spacing:.09em;text-transform:uppercase;color:#d8b4fe">Nouveautés AtriumOne</td></tr></table></td></tr><tr><td class="pad" style="padding:42px 38px 24px;background:#f7f1ff"><div style="display:inline-block;padding:7px 12px;border-radius:999px;background:#ede3ff;color:#6d28d9;font-size:11px;font-weight:800">${escapeHtml(version)}</div><h1 class="title" style="margin:18px 0 12px;font-size:38px;line-height:1.12;letter-spacing:-.03em;color:#211432">${escapeHtml(release.title)}</h1><p style="margin:0;font-size:16px;line-height:1.7;color:#6b617f">${escapeHtml(intro)}</p></td></tr>${release.description ? `<tr><td class="pad" style="padding:24px 38px 28px;font-size:15px;line-height:1.75;color:#4f4858">${escapeHtml(release.description).replaceAll("\n", "<br>")}</td></tr>` : ""}${section("Nouveautés", releaseList(release.highlights), "#7c3aed")}${section("Améliorations", releaseList(release.improvements), "#0f8a5f")}${section("Corrections", releaseList(release.fixes), "#c05a2b")}<tr><td align="center" style="padding:8px 38px 42px"><a href="${escapeHtml(base)}" style="display:inline-block;border-radius:999px;background:#6e4de0;padding:15px 26px;color:#ffffff;text-decoration:none;font-size:14px;font-weight:800">Découvrir AtriumOne</a></td></tr><tr><td style="padding:24px 38px;background:#211432;text-align:center;font-size:12px;line-height:1.6;color:#bfb3cd">AtriumOne · L’assistant intelligent des commerces de proximité<br><a href="${escapeHtml(base)}" style="color:#d8b4fe">Accéder à AtriumOne</a></td></tr></table></td></tr></table></body></html>`;
  return sanitizeEmailHtml(html);
}
