"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import type { CrmAppointment, CrmTask } from "@/lib/crm/types";

type View = "today" | "day" | "week" | "month";
const iso = (date: Date) => { const local = new Date(date.getTime() - date.getTimezoneOffset() * 60000); return local.toISOString().slice(0, 10); };
const addDays = (date: Date, count: number) => { const next = new Date(date); next.setDate(next.getDate() + count); return next; };

export function CalendarWorkspace({ initialTasks, initialAppointments }: { initialTasks: CrmTask[]; initialAppointments: CrmAppointment[] }) {
  const [tasks, setTasks] = useState(initialTasks); const [appointments] = useState(initialAppointments); const [view, setView] = useState<View>("today"); const [anchor, setAnchor] = useState(new Date());
  const dates = useMemo(() => {
    if (view === "today" || view === "day") return [iso(anchor)];
    if (view === "week") { const start = new Date(anchor); const day = (start.getDay() + 6) % 7; start.setDate(start.getDate() - day); return Array.from({ length: 7 }, (_, index) => iso(addDays(start, index))); }
    const start = new Date(anchor.getFullYear(), anchor.getMonth(), 1); const end = new Date(anchor.getFullYear(), anchor.getMonth() + 1, 0); return Array.from({ length: end.getDate() }, (_, index) => iso(new Date(anchor.getFullYear(), anchor.getMonth(), index + 1)));
  }, [view, anchor]);
  async function toggleTask(task: CrmTask) { const response = await fetch(`/api/crm/tasks/${task.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ completed: !task.completed }) }); if (response.ok) { const data = await response.json(); setTasks((current) => current.map((item) => item.id === task.id ? { ...item, ...data } : item)); } }
  async function deleteTask(id: string) { if (confirm("Supprimer cette tâche ?") && (await fetch(`/api/crm/tasks/${id}`, { method: "DELETE" })).ok) setTasks((current) => current.filter((item) => item.id !== id)); }
  function move(direction: number) { const days = view === "week" ? 7 : 1; if (view === "month") setAnchor(new Date(anchor.getFullYear(), anchor.getMonth() + direction, 1)); else setAnchor(addDays(anchor, direction * days)); }
  const todayTasks = tasks.filter((task) => task.due_date === iso(new Date()) && !task.completed);
  return <div className="space-y-4 p-5 lg:p-8">
    <section className="rounded-xl border border-[#E8E4DB] bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-1 rounded-lg bg-[#F3F0EB] p-1">{([['today','Aujourd’hui'],['day','Jour'],['week','Semaine'],['month','Mois']] as const).map(([key,label]) => <button key={key} onClick={() => setView(key)} className={`rounded-md px-3 py-2 text-xs font-black ${view === key ? "bg-white text-[#4C1D95] shadow-sm" : "text-[#6B617F]"}`}>{label}</button>)}</div><div className="flex items-center gap-2"><button onClick={() => move(-1)} className="ao-btn-secondary h-9 w-9">‹</button><button onClick={() => setAnchor(new Date())} className="ao-btn-secondary h-9 px-3 text-xs font-black">Aujourd’hui</button><button onClick={() => move(1)} className="ao-btn-secondary h-9 w-9">›</button></div></div></section>
    {(view === "today") ? <section className="rounded-xl border border-[#E8E4DB] bg-white p-4"><h2 className="text-sm font-black">Mes tâches aujourd’hui</h2><div className="mt-3 grid gap-3 lg:grid-cols-2"><TaskList title="Avec horaire" tasks={todayTasks.filter((task) => task.due_time)} onToggle={toggleTask} onDelete={deleteTask} /><TaskList title="Sans horaire" tasks={todayTasks.filter((task) => !task.due_time)} onToggle={toggleTask} onDelete={deleteTask} /></div></section> : null}
    <section className={`grid gap-2 ${view === "week" ? "lg:grid-cols-7" : view === "month" ? "sm:grid-cols-2 lg:grid-cols-7" : "grid-cols-1"}`}>{dates.map((date) => { const dayTasks = tasks.filter((task) => task.due_date === date); const dayAppointments = appointments.filter((item) => item.appointment_date === date); return <article key={date} className={`min-h-[150px] rounded-xl border bg-white p-3 ${date === iso(new Date()) ? "border-[#A855F7]" : "border-[#E8E4DB]"}`}><div className="mb-3 text-xs font-black capitalize">{new Date(`${date}T12:00:00`).toLocaleDateString("fr-FR", { weekday: "short", day: "numeric", month: view === "month" ? undefined : "short" })}</div><div className="space-y-1.5">{[...dayAppointments.map((item) => ({ key: `a-${item.id}`, time: item.appointment_time.slice(0,5), label: `${item.type} — ${item.crm_leads?.name ?? "Lead"}`, leadId: item.lead_id, tone: "bg-[#F3E8FF] text-[#4C1D95]" })), ...dayTasks.map((task) => ({ key: `t-${task.id}`, time: task.due_time?.slice(0,5) ?? "Toute la journée", label: task.title, leadId: task.lead_id, tone: task.completed ? "bg-gray-100 text-gray-500 line-through" : "bg-amber-50 text-amber-800" }))].sort((a,b) => a.time.localeCompare(b.time)).map((item) => <Link key={item.key} href={`/crm/leads/${item.leadId}`} className={`block rounded-md p-2 text-[10px] font-bold ${item.tone}`}><span className="block font-black">{item.time}</span>{item.label}</Link>)}{!dayTasks.length && !dayAppointments.length ? <div className="text-[10px] text-[#AAA19A]">Aucun événement</div> : null}</div></article>; })}</section>
  </div>;
}
function TaskList({ title, tasks, onToggle, onDelete }: { title: string; tasks: CrmTask[]; onToggle: (task: CrmTask) => void; onDelete: (id: string) => void }) { return <div><h3 className="mb-2 text-xs font-black text-[#6B617F]">{title}</h3><div className="space-y-2">{tasks.map((task) => <div key={task.id} className="flex items-center gap-2 rounded-lg border border-[#E8E4DB] p-2.5"><input type="checkbox" checked={task.completed} onChange={() => void onToggle(task)} /><Link href={`/crm/leads/${task.lead_id}`} className="min-w-0 flex-1"><div className="truncate text-xs font-black">{task.due_time?.slice(0,5)} {task.title}</div><div className="text-[10px] text-[#8B7AA8]">{task.crm_leads?.name}</div></Link><button onClick={() => { const date = prompt("Nouvelle date (AAAA-MM-JJ)", task.due_date); if (date) fetch(`/api/crm/tasks/${task.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ due_date: date }) }).then(() => location.reload()); }} className="text-[10px] font-bold">Replanifier</button><button onClick={() => void onDelete(task.id)} className="text-[10px] font-bold text-red-600">Supprimer</button></div>)}{!tasks.length ? <div className="rounded-lg border border-dashed p-3 text-center text-xs text-[#8B7AA8]">Aucune tâche.</div> : null}</div></div>; }
