"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { sortCalendarTasks } from "@/lib/crm/logic";
import type { CrmEvent, CrmTask } from "@/lib/crm/types";

type View = "today" | "day" | "week" | "month";
const iso = (date: Date) => { const local = new Date(date.getTime() - date.getTimezoneOffset() * 60000); return local.toISOString().slice(0, 10); };
const addDays = (date: Date, count: number) => { const next = new Date(date); next.setDate(next.getDate() + count); return next; };
const fullDate = (date: string) => new Date(`${date}T12:00:00`).toLocaleDateString("fr-FR", { weekday: "long", day: "numeric", month: "long", year: "numeric" });

export function CalendarWorkspace({ initialTasks, initialEvents }: { initialTasks: CrmTask[]; initialEvents: CrmEvent[] }) {
  const [tasks, setTasks] = useState(initialTasks);
  const [events] = useState(initialEvents);
  const [view, setView] = useState<View>("month");
  const [anchor, setAnchor] = useState(new Date());
  const [selectedDay, setSelectedDay] = useState<string | null>(null);
  const monthYear = anchor.toLocaleDateString("fr-FR", { month: "long", year: "numeric" });
  const dates = useMemo(() => {
    if (view === "today" || view === "day") return [iso(anchor)];
    if (view === "week") { const start = new Date(anchor); const day = (start.getDay() + 6) % 7; start.setDate(start.getDate() - day); return Array.from({ length: 7 }, (_, index) => iso(addDays(start, index))); }
    const end = new Date(anchor.getFullYear(), anchor.getMonth() + 1, 0); return Array.from({ length: end.getDate() }, (_, index) => iso(new Date(anchor.getFullYear(), anchor.getMonth(), index + 1)));
  }, [view, anchor]);

  async function toggleTask(task: CrmTask) { const response = await fetch(`/api/crm/tasks/${task.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ completed: !task.completed }) }); if (response.ok) { const data = await response.json(); setTasks((current) => current.map((item) => item.id === task.id ? { ...item, ...data } : item)); } }
  async function deleteTask(id: string) { if (confirm("Supprimer cette tâche ?") && (await fetch(`/api/crm/tasks/${id}`, { method: "DELETE" })).ok) setTasks((current) => current.filter((item) => item.id !== id)); }
  function move(direction: number) { const days = view === "week" ? 7 : 1; if (view === "month") setAnchor(new Date(anchor.getFullYear(), anchor.getMonth() + direction, 1)); else setAnchor(addDays(anchor, direction * days)); }
  const today = iso(new Date());
  const todayTasks = sortCalendarTasks(tasks.filter((task) => task.due_date === today));

  return <div className="space-y-4 p-5 lg:p-8">
    <section className="rounded-xl border border-[#E8E4DB] bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex gap-1 rounded-lg bg-[#F3F0EB] p-1">{([['today','Aujourd’hui'],['day','Jour'],['week','Semaine'],['month','Mois']] as const).map(([key,label]) => <button key={key} onClick={() => { setView(key); if (key === "today") setAnchor(new Date()); }} className={`rounded-md px-3 py-2 text-xs font-black ${view === key ? "bg-white text-[#4C1D95] shadow-sm" : "text-[#6B617F]"}`}>{label}</button>)}</div><div className="flex items-center gap-3"><button aria-label="Période précédente" onClick={() => move(-1)} className="ao-btn-secondary h-9 w-9 text-lg">‹</button><h2 className="min-w-[170px] text-center text-lg font-black capitalize text-[#2E1065]">{monthYear}</h2><button aria-label="Période suivante" onClick={() => move(1)} className="ao-btn-secondary h-9 w-9 text-lg">›</button><button onClick={() => setAnchor(new Date())} className="ao-btn-secondary h-9 px-3 text-xs font-black">Aujourd’hui</button></div></div></section>

    {view === "today" ? <section className="rounded-xl border border-[#E8E4DB] bg-white p-4"><h2 className="text-sm font-black">Mes tâches aujourd’hui</h2><div className="mt-3 grid gap-3 lg:grid-cols-2"><TaskList title="Avec horaire" tasks={todayTasks.filter((task) => task.due_time)} onToggle={toggleTask} onDelete={deleteTask} /><TaskList title="Sans horaire" tasks={todayTasks.filter((task) => !task.due_time)} onToggle={toggleTask} onDelete={deleteTask} /></div></section> : null}

    <section className={`grid gap-2 ${view === "week" ? "lg:grid-cols-7" : view === "month" ? "sm:grid-cols-2 lg:grid-cols-7" : "grid-cols-1"}`}>{dates.map((date) => { const dayTasks = sortCalendarTasks(tasks.filter((task) => task.due_date === date)); const dayEvents = events.filter((item) => item.event_date === date).sort((a,b) => (a.event_time ?? "99:99").localeCompare(b.event_time ?? "99:99")); return <article key={date} className={`min-h-[155px] rounded-xl border bg-white p-3 ${date === today ? "border-[#A855F7] ring-1 ring-[#E9D5FF]" : "border-[#E8E4DB]"}`}><button onClick={() => setSelectedDay(date)} className="mb-3 w-full text-left text-xs font-black capitalize hover:text-[#7C3AED]">{new Date(`${date}T12:00:00`).toLocaleDateString("fr-FR", { weekday: "short", day: "numeric", month: view === "month" ? undefined : "short", year: view === "day" ? "numeric" : undefined })}</button><div className="space-y-1.5">{dayEvents.map((item) => <Link key={item.id} href={`/crm/leads/${item.lead_id}`} className={`block rounded-md p-2 text-[10px] font-bold ${['R1','R2','R3'].includes(item.type) ? "bg-gradient-to-r from-violet-600 to-fuchsia-500 text-white shadow-sm" : "bg-cyan-50 text-cyan-900"}`}><span className="block font-black">{item.event_time?.slice(0,5) ?? "Toute la journée"}</span>{item.title}</Link>)}{dayTasks.map((task) => <div key={task.id} className={`flex gap-1.5 rounded-md p-2 text-[10px] font-bold ${task.completed ? "bg-gray-100 text-gray-500" : "bg-amber-50 text-amber-800"}`}><input aria-label={`Terminer ${task.title}`} type="checkbox" checked={task.completed} onChange={() => void toggleTask(task)} /><Link href={`/crm/leads/${task.lead_id}`} className={task.completed ? "line-through" : ""}><span className="block font-black">{task.due_time?.slice(0,5) ?? "Sans horaire"}</span>{task.title}</Link></div>)}{!dayTasks.length && !dayEvents.length ? <button onClick={() => setSelectedDay(date)} className="text-[10px] text-[#AAA19A]">Aucun élément</button> : null}</div></article>; })}</section>

    {selectedDay ? <div className="ao-modal-backdrop" onMouseDown={(event) => { if (event.currentTarget === event.target) setSelectedDay(null); }}><div className="ao-modal-content max-w-2xl p-5"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-wider text-[#8B7AA8]">Vue jour</div><h2 className="text-xl font-black capitalize">Tâches du {fullDate(selectedDay)}</h2></div><button onClick={() => setSelectedDay(null)}>✕</button></div><DayPanel date={selectedDay} tasks={tasks} events={events} onToggle={toggleTask} onDelete={deleteTask} /></div></div> : null}
  </div>;
}

function DayPanel({ date, tasks, events, onToggle, onDelete }: { date: string; tasks: CrmTask[]; events: CrmEvent[]; onToggle: (task: CrmTask) => void; onDelete: (id: string) => void }) { const sorted = sortCalendarTasks(tasks.filter((task) => task.due_date === date)); const timed = sorted.filter((task) => task.due_time); const untimed = sorted.filter((task) => !task.due_time); const dayEvents = events.filter((item) => item.event_date === date).sort((a,b) => (a.event_time ?? "99:99").localeCompare(b.event_time ?? "99:99")); return <div className="mt-5 space-y-5">{dayEvents.length ? <div><h3 className="mb-2 text-xs font-black text-[#6B617F]">Événements</h3><div className="space-y-2">{dayEvents.map((item) => <Link key={item.id} href={`/crm/leads/${item.lead_id}`} className={`block rounded-lg p-3 text-xs font-black ${['R1','R2','R3'].includes(item.type) ? "bg-gradient-to-r from-violet-600 to-fuchsia-500 text-white" : "bg-cyan-50 text-cyan-900"}`}>{item.event_time?.slice(0,5) ?? "—"} — {item.title}</Link>)}</div></div> : null}<TaskList title="Avec horaire" tasks={timed} onToggle={onToggle} onDelete={onDelete} /><TaskList title="Sans horaire" tasks={untimed} onToggle={onToggle} onDelete={onDelete} /></div>; }
function TaskList({ title, tasks, onToggle, onDelete }: { title: string; tasks: CrmTask[]; onToggle: (task: CrmTask) => void; onDelete: (id: string) => void }) { return <div><h3 className="mb-2 text-xs font-black text-[#6B617F]">{title}</h3><div className="space-y-2">{tasks.map((task) => <div key={task.id} className={`flex items-center gap-2 rounded-lg border border-[#E8E4DB] p-2.5 ${task.completed ? "bg-gray-50 text-gray-500" : ""}`}><input type="checkbox" checked={task.completed} onChange={() => void onToggle(task)} /><Link href={`/crm/leads/${task.lead_id}`} className="min-w-0 flex-1"><div className={`truncate text-xs font-black ${task.completed ? "line-through" : ""}`}>{task.due_time?.slice(0,5)} {task.title}</div><div className="text-[10px] text-[#8B7AA8]">{task.crm_leads?.name}{task.completed_at ? ` · Terminée ${new Date(task.completed_at).toLocaleString("fr-FR")}` : ""}</div></Link><button onClick={() => { const date = prompt("Nouvelle date (AAAA-MM-JJ)", task.due_date); if (date) fetch(`/api/crm/tasks/${task.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ due_date: date }) }).then(() => location.reload()); }} className="text-[10px] font-bold">Replanifier</button><button onClick={() => void onDelete(task.id)} className="text-[10px] font-bold text-red-600">Supprimer</button></div>)}{!tasks.length ? <div className="rounded-lg border border-dashed p-3 text-center text-xs text-[#8B7AA8]">Aucune tâche.</div> : null}</div></div>; }
