"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import { COMMERCIAL_STATUSES, CRM_APPOINTMENT_TYPES, CRM_MODULES, CRM_TASK_TYPES, LOST_REASONS, MODULE_LABELS, type BusinessAccess, type CrmAppointment, type CrmLead, type CrmTask } from "@/lib/crm/types";

type Note = { id: string; content: string; created_at: string; updated_at: string; created_by: string | null };
type Activity = { id: string; type: string; metadata: Record<string, unknown>; created_at: string };
type Candidate = { businessId: string; userId: string; businessName: string; email: string | null; reason: string };
type Account = { email: string | null; createdAt: string | null; lastSignInAt: string | null } | null;
const formatDateTime = (value?: string | null) => value ? new Date(value).toLocaleString("fr-FR", { dateStyle: "medium", timeStyle: "short" }) : "Non disponible";

export function LeadDetailWorkspace({ initial }: { initial: { lead: CrmLead; notes: Note[]; tasks: CrmTask[]; appointments: CrmAppointment[]; activity: Activity[]; access: BusinessAccess | null; modules: Array<{ module_key: string; enabled: boolean }>; account: Account; candidates: Candidate[] } }) {
  const router = useRouter();
  const [lead, setLead] = useState(initial.lead); const [notes, setNotes] = useState(initial.notes); const [tasks, setTasks] = useState(initial.tasks); const [appointments, setAppointments] = useState(initial.appointments); const [activity] = useState(initial.activity);
  const [editingIdentity, setEditingIdentity] = useState(false); const [showTask, setShowTask] = useState(false); const [showAppointment, setShowAppointment] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const [accountEnabled, setAccountEnabled] = useState(initial.access?.account_enabled ?? false); const [onboardingStatus, setOnboardingStatus] = useState(initial.access?.onboarding_status ?? (lead.business_id ? "pending" : "pending")); const [modules, setModules] = useState<Record<string, boolean>>(Object.fromEntries(CRM_MODULES.map((key) => [key, initial.modules.find((row) => row.module_key === key)?.enabled ?? false])));
  const nextAppointment = useMemo(() => appointments.filter((item) => `${item.appointment_date}T${item.appointment_time}` >= new Date().toISOString().slice(0, 19)).sort((a,b) => `${a.appointment_date}${a.appointment_time}`.localeCompare(`${b.appointment_date}${b.appointment_time}`))[0] ?? null, [appointments]);

  async function patchLead(update: Record<string, unknown>) { const response = await fetch(`/api/crm/leads/${lead.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(update) }); const data = await response.json(); if (!response.ok) return setMessage(data.error?.message ?? "Modification impossible."); setLead((current) => ({ ...current, ...data })); setMessage("Modifications enregistrées."); }
  async function saveIdentity(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const body = Object.fromEntries(new FormData(event.currentTarget).entries()); await patchLead(body); setEditingIdentity(false); }
  async function addNote(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const content = String(new FormData(form).get("content") ?? ""); const response = await fetch(`/api/crm/leads/${lead.id}/notes`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content }) }); if (response.ok) { const created = await response.json(); setNotes((current) => [created, ...current]); form.reset(); } }
  async function editNote(note: Note) { const content = prompt("Modifier la note", note.content); if (!content) return; const response = await fetch(`/api/crm/notes/${note.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content }) }); if (response.ok) { const data = await response.json(); setNotes((current) => current.map((item) => item.id === note.id ? data : item)); } }
  async function deleteNote(id: string) { if (!confirm("Supprimer cette note ?")) return; if ((await fetch(`/api/crm/notes/${id}`, { method: "DELETE" })).ok) setNotes((current) => current.filter((item) => item.id !== id)); }
  async function addTask(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const body = Object.fromEntries(new FormData(form).entries()); const response = await fetch(`/api/crm/leads/${lead.id}/tasks`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (response.ok) { const created = await response.json(); setTasks((current) => [...current, created]); setShowTask(false); form.reset(); } }
  async function updateTask(id: string, update: Record<string, unknown>) { const response = await fetch(`/api/crm/tasks/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(update) }); if (response.ok) { const data = await response.json(); setTasks((current) => current.map((item) => item.id === id ? data : item)); } }
  async function editTask(task: CrmTask) { const title = prompt("Titre de la tâche", task.title); if (!title) return; const description = prompt("Description facultative", task.description ?? ""); await updateTask(task.id, { title, description }); }
  async function deleteTask(id: string) { if (confirm("Supprimer cette tâche ?") && (await fetch(`/api/crm/tasks/${id}`, { method: "DELETE" })).ok) setTasks((current) => current.filter((item) => item.id !== id)); }
  async function addAppointment(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const body = Object.fromEntries(new FormData(form).entries()); const response = await fetch(`/api/crm/leads/${lead.id}/appointments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (response.ok) { const created = await response.json(); setAppointments((current) => [...current, created]); setShowAppointment(false); form.reset(); } }
  async function deleteAppointment(id: string) { if (confirm("Supprimer ce RDV ?") && (await fetch(`/api/crm/appointments/${id}`, { method: "DELETE" })).ok) setAppointments((current) => current.filter((item) => item.id !== id)); }
  async function updateAppointment(item: CrmAppointment, mode: "edit" | "reschedule") { const body: Record<string, unknown> = {}; if (mode === "reschedule") { const date = prompt("Nouvelle date (AAAA-MM-JJ)", item.appointment_date); if (!date) return; const time = prompt("Nouvelle heure (HH:MM)", item.appointment_time.slice(0,5)); if (!time) return; body.appointment_date = date; body.appointment_time = time; } else { const notes = prompt("Notes du rendez-vous", item.notes ?? ""); if (notes === null) return; const result = prompt("Résultat", item.result ?? ""); if (result === null) return; body.notes = notes; body.result = result; } const response = await fetch(`/api/crm/appointments/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (response.ok) { const data = await response.json(); setAppointments((current) => current.map((currentItem) => currentItem.id === item.id ? data : currentItem)); } }
  async function saveAccess(businessId?: string) { if (!lead.business_id && !businessId) return; if (!initial.access?.account_enabled && accountEnabled && !confirm("Activer AtriumOne pour ce client ?")) return; const manual = Boolean(businessId); if (manual && !confirm("Associer ce compte AtriumOne à ce prospect ?")) return; const response = await fetch(`/api/crm/leads/${lead.id}/access`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ businessId, manualConfirmed: manual, accountEnabled, onboardingStatus, modules }) }); const data = await response.json(); if (!response.ok) return setMessage(data.error?.message ?? "Accès non enregistrés."); if (data.businessId && !lead.business_id) setLead((current) => ({ ...current, business_id: data.businessId })); setAccountEnabled(data.accountEnabled); setOnboardingStatus(data.onboardingStatus); setModules(data.modules); setMessage("Accès AtriumOne enregistrés."); router.refresh(); }

  return <div>
    <header className="border-b border-[#E8E4DB] bg-white px-5 py-5 lg:px-8"><div className="mb-3"><Link href="/crm/leads" className="text-xs font-black text-[#6B617F]">← Base de données</Link></div><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-black tracking-[-.03em]">{lead.name}</h1><span className="rounded-full bg-[#F3E8FF] px-2.5 py-1 text-[10px] font-black text-[#4C1D95]">{lead.lead_source}</span></div><p className="mt-1 text-sm font-semibold text-[#6B617F]">{lead.business_type ?? "Métier non renseigné"} · {lead.city ?? "Ville inconnue"}</p></div><div className="flex gap-2"><select value={lead.commercial_status} onChange={(event) => void patchLead({ commercial_status: event.target.value })} className="ao-select h-10 px-3 text-xs font-black">{COMMERCIAL_STATUSES.map((status) => <option key={status}>{status}</option>)}</select><button onClick={() => { if (confirm("Archiver ce lead ?")) void patchLead({ archived_at: new Date().toISOString() }).then(() => router.push("/crm/leads")); }} className="ao-btn-secondary px-3 text-xs font-black">Archiver</button></div></div>{message ? <div className="mt-3 rounded-lg bg-[#F3E8FF] px-3 py-2 text-xs font-bold text-[#4C1D95]">{message}</div> : null}</header>
    <div className="grid gap-4 p-5 lg:grid-cols-[minmax(0,1.1fr)_minmax(0,1fr)_340px] lg:p-8">
      <div className="space-y-4">
        <Section title="Identité" action={<button onClick={() => setEditingIdentity(!editingIdentity)} className="text-xs font-black text-[#4C1D95]">{editingIdentity ? "Annuler" : "Modifier"}</button>}>
          {editingIdentity ? <form onSubmit={saveIdentity} className="grid gap-3 sm:grid-cols-2">{[["name","Nom"],["business_type","Métier"],["address","Adresse"],["city","Ville"],["postal_code","Code postal"],["phone","Téléphone"],["email","Email"],["website","Site"]].map(([key,label]) => <label key={key} className={`ao-label ${key === "address" ? "sm:col-span-2" : ""}`}>{label}<input name={key} defaultValue={String(lead[key as keyof CrmLead] ?? "")} className="ao-input h-9 px-2.5" /></label>)}<button className="ao-btn-primary h-9 px-3 text-xs font-black sm:col-span-2">Enregistrer</button></form> : <div className="grid gap-x-5 gap-y-3 sm:grid-cols-2"><Fact label="Métier" value={lead.business_type} /><Fact label="Adresse" value={[lead.address, lead.postal_code, lead.city].filter(Boolean).join(", ")} /><Fact label="Téléphone" value={lead.phone} href={lead.phone ? `tel:${lead.phone}` : undefined} /><Fact label="Email" value={lead.email} href={lead.email ? `mailto:${lead.email}` : undefined} /><Fact label="Site" value={lead.website} href={lead.website ?? undefined} /><Fact label="Google Maps" value={lead.google_maps_url ? "Ouvrir la fiche" : null} href={lead.google_maps_url ?? undefined} /><Fact label="Note Google" value={lead.google_rating ? `${lead.google_rating} / 5` : null} /><Fact label="Nombre d’avis" value={lead.google_reviews_count?.toString()} /><Fact label="Date fiche Google" value={lead.google_profile_created_at ? formatDateTime(lead.google_profile_created_at) : "Non disponible"} /><Fact label="Ajouté le" value={formatDateTime(lead.created_at)} /></div>}
        </Section>
        {nextAppointment ? <div className="rounded-xl border border-[#C4B5FD] bg-[#F5F3FF] p-4"><div className="text-[10px] font-black uppercase tracking-wider text-[#7C3AED]">Prochain RDV</div><div className="mt-1 text-base font-black">{nextAppointment.type}</div><div className="mt-1 text-xs font-bold text-[#6B617F]">{new Date(`${nextAppointment.appointment_date}T${nextAppointment.appointment_time}`).toLocaleString("fr-FR", { dateStyle: "full", timeStyle: "short" })} · {nextAppointment.duration_minutes} min</div></div> : null}
        <Section title="Notes" action={null}><form onSubmit={addNote} className="flex gap-2"><textarea name="content" required placeholder="Ajouter une note commerciale…" rows={2} className="ao-input flex-1 resize-none px-3 py-2 text-sm" /><button className="ao-btn-primary self-end px-3 py-2 text-xs font-black">Ajouter</button></form><div className="mt-3 space-y-2">{notes.map((note) => <article key={note.id} className="rounded-lg bg-[#FAF9F7] p-3"><p className="whitespace-pre-wrap text-sm leading-6">{note.content}</p><div className="mt-2 flex justify-between text-[10px] font-semibold text-[#8B7AA8]"><span>{formatDateTime(note.created_at)} · {note.created_by ? "louisdacre@gmail.com" : "Système"}</span><span><button onClick={() => void editNote(note)} className="mr-2">Modifier</button><button onClick={() => void deleteNote(note.id)} className="text-red-600">Supprimer</button></span></div></article>)}{!notes.length ? <Empty text="Aucune note." /> : null}</div></Section>
        <Section title="Tâches commerciales" action={<button onClick={() => setShowTask(!showTask)} className="text-xs font-black text-[#4C1D95]">+ Ajouter une tâche</button>}>{showTask ? <TaskForm onSubmit={addTask} /> : null}<div className="mt-3 space-y-2">{tasks.map((task) => <div key={task.id} className={`flex items-start gap-3 rounded-lg border p-3 ${task.completed ? "border-[#E8E4DB] bg-[#FAF9F7] opacity-60" : "border-[#E8E4DB]"}`}><input type="checkbox" checked={task.completed} onChange={(event) => void updateTask(task.id, { completed: event.target.checked })} className="mt-1" /><div className="min-w-0 flex-1"><div className="text-sm font-black">{task.title}</div><div className="mt-1 text-[11px] font-semibold text-[#6B617F]">{task.type} · {new Date(`${task.due_date}T12:00:00`).toLocaleDateString("fr-FR")}{task.due_time ? ` à ${task.due_time.slice(0,5)}` : " · Sans horaire"}</div>{task.description ? <p className="mt-1 text-xs text-[#6B617F]">{task.description}</p> : null}</div><button onClick={() => void editTask(task)} className="text-[10px] font-bold">Modifier</button><button onClick={() => { const due_date = prompt("Nouvelle date (AAAA-MM-JJ)", task.due_date); if (due_date) void updateTask(task.id, { due_date }); }} className="text-[10px] font-bold">Replanifier</button><button onClick={() => void deleteTask(task.id)} className="text-[10px] font-bold text-red-600">Supprimer</button></div>)}{!tasks.length ? <Empty text="Aucune tâche." /> : null}</div></Section>
        <Section title="Rendez-vous" action={<button onClick={() => setShowAppointment(!showAppointment)} className="text-xs font-black text-[#4C1D95]">+ Ajouter un RDV</button>}>{showAppointment ? <AppointmentForm onSubmit={addAppointment} /> : null}<div className="mt-3 space-y-2">{appointments.map((item) => <div key={item.id} className="flex items-start justify-between gap-3 rounded-lg border border-[#E8E4DB] p-3"><div className="min-w-0 flex-1"><div className="text-sm font-black">{item.title || item.type}</div><div className="mt-1 text-[11px] font-semibold text-[#6B617F]">{item.type} · {new Date(`${item.appointment_date}T${item.appointment_time}`).toLocaleString("fr-FR", { dateStyle: "medium", timeStyle: "short" })} · {item.duration_minutes} min</div>{item.notes ? <p className="mt-1 text-xs text-[#6B617F]">{item.notes}</p> : null}</div><button onClick={() => void updateAppointment(item, "edit")} className="text-[10px] font-bold">Modifier</button><button onClick={() => void updateAppointment(item, "reschedule")} className="text-[10px] font-bold">Replanifier</button><button onClick={() => void deleteAppointment(item.id)} className="text-[10px] font-bold text-red-600">Supprimer</button></div>)}{!appointments.length ? <Empty text="Aucun rendez-vous." /> : null}</div></Section>
      </div>
      <div className="space-y-4">
        {lead.commercial_status === "Signé" ? <Section title="Signature"><SimpleLeadForm submitLabel="Enregistrer la vente" onSubmit={patchLead} fields={[{name:"signed_at",label:"Date de signature",type:"date",value:lead.signed_at},{name:"signed_offer",label:"Offre",value:lead.signed_offer},{name:"monthly_value",label:"Prix mensuel",type:"number",value:lead.monthly_value},{name:"mrr",label:"MRR",type:"number",value:lead.mrr},{name:"contract_started_at",label:"Date de début",type:"date",value:lead.contract_started_at},{name:"signed_comment",label:"Commentaire",value:lead.signed_comment}]} /></Section> : null}
        {lead.commercial_status === "Perdu" ? <Section title="Opportunité perdue"><form onSubmit={(event) => { event.preventDefault(); void patchLead(Object.fromEntries(new FormData(event.currentTarget).entries())); }} className="space-y-3"><label className="ao-label">Raison<select name="lost_reason" defaultValue={lead.lost_reason ?? ""} className="ao-select h-9 px-2"><option value="">Choisir</option>{LOST_REASONS.map((reason) => <option key={reason}>{reason}</option>)}</select></label><label className="ao-label">Commentaire<textarea name="lost_comment" defaultValue={lead.lost_comment ?? ""} className="ao-input px-2 py-2" /></label><input type="hidden" name="lost_at" value={lead.lost_at ?? new Date().toISOString().slice(0,10)} /><button className="ao-btn-primary px-3 py-2 text-xs font-black">Enregistrer</button></form></Section> : null}
        <Section title="Timeline"><div className="relative space-y-0 before:absolute before:bottom-2 before:left-[7px] before:top-2 before:w-px before:bg-[#E8E4DB]">{activity.map((item) => <div key={item.id} className="relative flex gap-3 py-2"><span className="mt-1.5 h-[15px] w-[15px] shrink-0 rounded-full border-[4px] border-white bg-[#A855F7] ring-1 ring-[#D8B4FE]" /><div><div className="text-xs font-black">{activityLabel(item)}</div><time className="mt-0.5 block text-[10px] font-semibold text-[#8B7AA8]">{formatDateTime(item.created_at)}</time></div></div>)}{!activity.length ? <Empty text="L’activité apparaîtra ici." /> : null}</div></Section>
      </div>
      <aside className="space-y-4">
        <Section title="Compte AtriumOne">
          <div className="space-y-3"><Fact label="État" value={!lead.business_id ? "Aucun compte" : onboardingStatus === "suspended" ? "Suspendu" : accountEnabled ? "Actif" : "En attente d’onboarding"} /><Fact label="Email du compte" value={initial.account?.email} /><Fact label="Date d’inscription" value={formatDateTime(initial.account?.createdAt)} /><Fact label="Dernière connexion" value={formatDateTime(initial.account?.lastSignInAt)} /></div>
          {lead.business_id ? <div className="mt-4 border-t border-[#E8E4DB] pt-4"><label className="flex items-center justify-between gap-3 text-sm font-black"><span>Activer AtriumOne</span><button type="button" role="switch" aria-checked={accountEnabled} onClick={() => setAccountEnabled(!accountEnabled)} className={`ao-toggle ${accountEnabled ? "ao-toggle-on" : "ao-toggle-off"}`}><span className={`ao-toggle-thumb ${accountEnabled ? "ao-toggle-thumb-on" : "ao-toggle-thumb-off"}`} /></button></label><label className="ao-label mt-3">Statut<select value={onboardingStatus} onChange={(e) => setOnboardingStatus(e.target.value as BusinessAccess["onboarding_status"])} className="ao-select h-9 px-2"><option value="pending">En attente d’onboarding</option><option value="active">Actif</option><option value="suspended">Suspendu</option></select></label><div className="mt-4 text-xs font-black">Modules activés</div><div className="mt-2 space-y-2">{CRM_MODULES.map((key) => <label key={key} className={`flex items-center gap-2 text-xs font-semibold ${!accountEnabled ? "text-[#8B7AA8]" : ""}`}><input type="checkbox" disabled={!accountEnabled} checked={modules[key]} onChange={(e) => setModules({ ...modules, [key]: e.target.checked })} />{MODULE_LABELS[key]}</label>)}</div><button onClick={() => void saveAccess()} className="ao-btn-primary mt-4 w-full px-3 py-2.5 text-xs font-black">Enregistrer les accès</button><p className="mt-2 text-[10px] leading-4 text-[#8B7AA8]">Le compte global désactivé écrase tous les droits modules.</p></div> : <div className="mt-4"><div className="text-xs font-black">Comptes AtriumOne potentiels</div>{initial.candidates.length ? <div className="mt-2 space-y-2">{initial.candidates.map((candidate) => <div key={candidate.businessId} className="rounded-lg border border-amber-200 bg-amber-50 p-2.5"><div className="text-xs font-black">{candidate.businessName}</div><div className="text-[10px] text-amber-800">{candidate.reason} · {candidate.email}</div><button onClick={() => void saveAccess(candidate.businessId)} className="mt-2 text-[11px] font-black text-[#4C1D95]">Associer</button></div>)}</div> : <Empty text="Aucun compte potentiel fiable." />}</div>}
        </Section>
        <Section title="Zone sensible"><button onClick={async () => { if (!confirm(`Supprimer définitivement ${lead.name} du CRM ? Le compte AtriumOne associé restera intact.`)) return; let response = await fetch(`/api/crm/leads/${lead.id}?permanent=1`, { method: "DELETE" }); if (response.status === 409 && confirm("Un compte AtriumOne est associé. Confirmer la suppression du lead uniquement ?")) response = await fetch(`/api/crm/leads/${lead.id}?permanent=1&confirm_account_preserved=1`, { method: "DELETE" }); if (response.ok) router.push("/crm/leads"); }} className="w-full rounded-lg border border-red-200 px-3 py-2 text-xs font-black text-red-700">Supprimer définitivement le lead</button><p className="mt-2 text-[10px] leading-4 text-[#8B7AA8]">Cette action ne supprime jamais le compte utilisateur AtriumOne.</p></Section>
      </aside>
    </div>
  </div>;
}

function Section({ title, action, children }: { title: string; action?: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-xl border border-[#E8E4DB] bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between gap-3"><h2 className="text-sm font-black">{title}</h2>{action}</div>{children}</section>; }
function Fact({ label, value, href }: { label: string; value?: string | null; href?: string }) { const content = value || "Non renseigné"; return <div><div className="text-[10px] font-black uppercase tracking-wide text-[#8B7AA8]">{label}</div>{href ? <a href={href} target={href.startsWith("http") ? "_blank" : undefined} rel="noreferrer" className="mt-0.5 block break-words text-xs font-bold text-[#4C1D95]">{content}</a> : <div className="mt-0.5 break-words text-xs font-bold">{content}</div>}</div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-lg border border-dashed border-[#D9D1C3] p-3 text-center text-xs font-semibold text-[#8B7AA8]">{text}</div>; }
function TaskForm({ onSubmit }: { onSubmit: (event: React.FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={onSubmit} className="grid gap-2 rounded-lg bg-[#FAF9F7] p-3 sm:grid-cols-2"><label className="ao-label">Titre<input name="title" required className="ao-input h-9 px-2" /></label><label className="ao-label">Type<select name="type" className="ao-select h-9 px-2">{CRM_TASK_TYPES.map((type) => <option key={type}>{type}</option>)}</select></label><label className="ao-label">Date<input name="due_date" type="date" required className="ao-input h-9 px-2" /></label><label className="ao-label">Heure facultative<input name="due_time" type="time" className="ao-input h-9 px-2" /></label><label className="ao-label sm:col-span-2">Description<textarea name="description" className="ao-input px-2 py-2" /></label><button className="ao-btn-primary px-3 py-2 text-xs font-black sm:col-span-2">Créer la tâche</button></form>; }
function AppointmentForm({ onSubmit }: { onSubmit: (event: React.FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={onSubmit} className="grid gap-2 rounded-lg bg-[#FAF9F7] p-3 sm:grid-cols-2"><label className="ao-label">Type<select name="type" className="ao-select h-9 px-2">{CRM_APPOINTMENT_TYPES.map((type) => <option key={type}>{type}</option>)}</select></label><label className="ao-label">Titre<input name="title" className="ao-input h-9 px-2" /></label><label className="ao-label">Date<input name="appointment_date" type="date" required className="ao-input h-9 px-2" /></label><label className="ao-label">Heure<input name="appointment_time" type="time" required className="ao-input h-9 px-2" /></label><label className="ao-label">Durée (min)<input name="duration_minutes" type="number" defaultValue="30" min="5" className="ao-input h-9 px-2" /></label><label className="ao-label">Résultat<input name="result" className="ao-input h-9 px-2" /></label><label className="ao-label sm:col-span-2">Notes<textarea name="notes" className="ao-input px-2 py-2" /></label><button className="ao-btn-primary px-3 py-2 text-xs font-black sm:col-span-2">Créer le RDV</button></form>; }
function SimpleLeadForm({ fields, onSubmit, submitLabel }: { fields: Array<{ name: string; label: string; type?: string; value: unknown }>; onSubmit: (update: Record<string, unknown>) => Promise<void>; submitLabel: string }) { return <form onSubmit={(event) => { event.preventDefault(); void onSubmit(Object.fromEntries(new FormData(event.currentTarget).entries())); }} className="grid gap-2 sm:grid-cols-2">{fields.map((field) => <label key={field.name} className="ao-label">{field.label}<input name={field.name} type={field.type ?? "text"} defaultValue={String(field.value ?? "")} step={field.type === "number" ? "0.01" : undefined} className="ao-input h-9 px-2" /></label>)}<button className="ao-btn-primary px-3 py-2 text-xs font-black sm:col-span-2">{submitLabel}</button></form>; }
function activityLabel(activity: Activity) { const labels: Record<string,string> = { lead_created: "Prospect ajouté au CRM", status_changed: `Statut → ${String(activity.metadata.to ?? "mis à jour")}`, note_added: "Note ajoutée", note_updated: "Note modifiée", note_deleted: "Note supprimée", task_created: `Tâche créée · ${String(activity.metadata.title ?? "")}`, task_completed: `Tâche terminée · ${String(activity.metadata.title ?? "")}`, task_updated: "Tâche mise à jour", task_deleted: "Tâche supprimée", appointment_created: "Rendez-vous créé", appointment_updated: "Rendez-vous modifié", appointment_deleted: "Rendez-vous supprimé", account_associated: "Compte AtriumOne associé", account_activated: "Compte AtriumOne activé", account_disabled: "Compte AtriumOne désactivé" }; return labels[activity.type] ?? activity.type.replaceAll("_", " "); }
